### ISSUE TITLE
Virtualenv python/pip error

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#148]
Error: New python executable in /srv/maverick/.virtualenvs/maverick-fcs/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /srv/maverick/.virtu...erick-fcs/bin/python - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 215, in main
  File "/srv/maverick/.virtualenvs/maverick-fcs/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /srv/maverick/.virtu...erick-fcs/bin/python - setuptools pkg_resources pip wheel failed with error code 1
Running virtualenv with interpreter /usr/bin/python
sh: 1: /srv/maverick/.virtualenvs/maverick-fcs/bin/pip: not found
sh: 1: /srv/maverick/.virtualenvs/maverick-fcs/bin/pip: not found

Error: /Stage[main]/Maverick-fcs/Python::Virtualenv[/srv/maverick/software/maverick-fcs]/Exec[python_virtualenv_/srv/maverick/.virtualenvs/maverick-fcs]/returns: change from notrun to 0 failed: New python executable in /srv/maverick/.virtualenvs/maverick-fcs/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /srv/maverick/.virtu...erick-fcs/bin/python - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 215, in main
  File "/srv/maverick/.virtualenvs/maverick-fcs/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /srv/maverick/.virtu...erick-fcs/bin/python - setuptools pkg_resources pip wheel failed with error code 1
Running virtualenv with interpreter /usr/bin/python
sh: 1: /srv/maverick/.virtualenvs/maverick-fcs/bin/pip: not found
sh: 1: /srv/maverick/.virtualenvs/maverick-fcs/bin/pip: not found

**Comment by fnoop** [comment]
Think this is because of the unsupported locale setting, run base::locale and make it a dependency.

**Comment by fnoop** [comment]
locale-gen "en_GB.UTF-8"
dpkg-reconfigure locales

**Comment by fnoop** [comment]
Should be dealt with in base::locale module instead using a locales module:
https://forge.puppet.com/saz/locales
