### ISSUE TITLE
Odroid ubuntu 16.04 pyric pip locale error

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#187]
```
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns: Traceback (most recent call last):
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns:   File "/usr/bin/pip", line 11, in <module>
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns:     sys.exit(main())
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns:   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns:     locale.setlocale(locale.LC_ALL, '')
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns:   File "/usr/lib/python2.7/locale.py", line 581, in setlocale
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns:     return _setlocale(category, locale)
Notice: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns: locale.Error: unsupported locale setting
Error: /usr/bin/pip install PyRIC returned 1 instead of one of [0]
Error: /Stage[bootstrap]/Base::Packages/Exec[install pyric]/returns: change from notrun to 0 failed: /usr/bin/pip install PyRIC returned 1 instead of one of [0]
```

**Comment by fnoop** [comment]
Move base::locale into bootstrap stage and make dependency of base::packages.
