### ISSUE TITLE
dronekit-la compile failing

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#192]
```
Error: /usr/bin/make -j7 >/srv/maverick/var/log/build/dronekit-la.build.log 2>&1 returned 2 instead of one of [0]
Error: /Stage[main]/Maverick_fc/Exec[compile-dronekit-la]/returns: change from notrun to 0 failed: /usr/bin/make -j7 >/srv/maverick/var/log/build/dronekit-la.build.log 2>&1 returned 2 instead of one of [0]
```

**Comment by fnoop** [comment]
```
Generating C implementation in directory c_library/ardupilotmega
Traceback (most recent call last):
  File "pymavlink/tools/mavgen.py", line 30, in <module>
    mavgen.mavgen(args, args.definitions)
  File "/srv/maverick/software/dronekit-la/modules/mavlink/pymavlink/generator/mavgen.py", line 104, in mavgen
    mavgen_c.generate(opts.output, xml)
  File "/srv/maverick/software/dronekit-la/modules/mavlink/pymavlink/generator/mavgen_c.py", line 628, in generate
    generate_one(basename, xml)
  File "/srv/maverick/software/dronekit-la/modules/mavlink/pymavlink/generator/mavgen_c.py", line 502, in generate_one
    mavparse.mkdir_p(directory)
  File "/srv/maverick/software/dronekit-la/modules/mavlink/pymavlink/generator/mavparse.py", line 403, in mkdir_p
    os.makedirs(dir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 'c_library'
Makefile:104: recipe for target 'modules/mavlink/c_library/protocol.h' failed
make: *** [modules/mavlink/c_library/protocol.h] Error 1
```

**Comment by fnoop** [comment]
dronekit-la being cloned as root, should be mav user
