### ISSUE TITLE
visiond should warn if .pid file stops startup

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#391]
Or test if another running process exists, if not remove the pid file and start anyway

**Comment by fnoop** [comment]
Also should be more graceful for stop and restart if process isn't already running:
```
 maverick-visiond restart
Starting maverick-visiond daemon
Traceback (most recent call last):
File "/srv/maverick/software/maverick/bin/maverick-visiond", line 643, in <module>
daemon_runner.do_action()
File "/usr/lib/python2.7/dist-packages/daemon/runner.py", line 267, in do_action
func(self)
File "/usr/lib/python2.7/dist-packages/daemon/runner.py", line 227, in _restart
self._stop()
File "/usr/lib/python2.7/dist-packages/daemon/runner.py", line 222, in _stop
self._terminate_daemon_process()
File "/usr/lib/python2.7/dist-packages/daemon/runner.py", line 198, in _terminate_daemon_process
os.kill(pid, signal.SIGTERM)
TypeError: an integer is required
```
