### ISSUE TITLE
Pi zero W configure hangs

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#418]
```
Maverick Environment:    dev
Proceeding to update system configuration - please be patient, this can take a while..

^CTraceback (most recent call last):
Exiting
  File "/srv/maverick/software/maverick/manifests/maverick-modules/base/facts.d/pip.py", line 13, in <module>
    _pips = pipoutput.communicate()[0].split()
  File "/usr/lib/python2.7/subprocess.py", line 799, in communicate
    Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/base/facts.d/pip.py as Facter::Util::Parser::ScriptParser facts: exitreturn self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1409, in _communicate

Fact file /srv/maverick/software/maverick/manifests/maverick-modules/base/facts.d/pip.py was parsed but returned an empty data set
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1463, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/beagle.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/beagle.py was parsed but returned an empty data set
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 68, in <module>
    import os
  File "/usr/lib/python2.7/os.py", line 717, in <module>
    import copy_reg as _copy_reg
  File "/usr/lib/python2.7/copy_reg.py", line 5, in <module>
    """
KeyboardInterrupt
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/camera.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/camera.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/filesystems.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/filesystems.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/joule.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/joule.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/odroid.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/odroid.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/raspberry.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_hardware/facts.d/raspberry.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_network/facts.d/activemanager.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_network/facts.d/activemanager.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_network/facts.d/netinfo.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_network/facts.d/netinfo.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_network/facts.d/udevnet.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_network/facts.d/udevnet.py was parsed but returned an empty data set
^CExiting
Failed to handle /srv/maverick/software/maverick/manifests/maverick-modules/maverick_cloud9/facts.d/cloud9.py as Facter::Util::Parser::ScriptParser facts: exit
Fact file /srv/maverick/software/maverick/manifests/maverick-modules/maverick_cloud9/facts.d/cloud9.py was parsed but returned an empty data set








Error: Undefined variable "raspberry_present" at /srv/maverick/software/maverick/manifests/maverick-modules/maverick_vision/manifests/gstreamer.pp:7 on node maverick-raspberry.fritz.box
Error: Undefined variable "raspberry_present" at /srv/maverick/software/maverick/manifests/maverick-modules/maverick_vision/manifests/gstreamer.pp:7 on node maverick-raspberry.fritz.box

```

**Comment by fnoop** [comment]
Cannot reproduce, closing for now.  May be related to https://github.com/fnoop/maverick/issues/137
