### ISSUE TITLE
MAVcesium on Raspberry fails

### ISSUE THREAD

**Issue by fnoop** [fnoop/maverick#421]
`STABILIZE> ERROR in command ['load', 'cesium']: 'module' object has no attribute 'OP_NO_TLSv1_1'`

**Comment by fnoop** [comment]
```
STABILIZE> module load cesium
STABILIZE> ERROR in command ['load', 'cesium']: 'module' object has no attribute 'OP_NO_TLSv1_1'
Traceback (most recent call last):
  File "/usr/local/bin/mavproxy.py", line 492, in process_stdin
    fn(args[1:])
  File "/usr/local/bin/mavproxy.py", line 320, in cmd_module
    load_module(args[1])
  File "/usr/local/bin/mavproxy.py", line 276, in load_module
    m = import_package(modpath)
  File "/usr/local/bin/mavproxy.py", line 403, in import_package
    mod = __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy/modules/mavproxy_cesium/__init__.py", line 18, in <module>
    from twisted.internet import reactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'
```

**Comment by fnoop** [comment]
Problem is pyOpenSSL needs upgrading.  For this, install_python_module() needs reworking so it can handle versions and updating.

**Comment by fnoop** [comment]
pyOpenSSL updated, now get this:
```
STABILIZE> :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Using config file at /usr/local/lib/python2.7/dist-packages/MAVProxy/modules/mavproxy_cesium/app/mavcesium_default.ini
ERROR in command ['load', 'cesium']: __init__() got an unexpected keyword argument 'root_path'
Traceback (most recent call last):
  File "/usr/local/bin/mavproxy.py", line 492, in process_stdin
    fn(args[1:])
  File "/usr/local/bin/mavproxy.py", line 320, in cmd_module
    load_module(args[1])
  File "/usr/local/bin/mavproxy.py", line 276, in load_module
    m = import_package(modpath)
  File "/usr/local/bin/mavproxy.py", line 403, in import_package
    mod = __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy/modules/mavproxy_cesium/__init__.py", line 22, in <module>
    from app import cesium_web_server # the Flask webapp
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy/modules/mavproxy_cesium/app/cesium_web_server.py", line 28, in <module>
    app = Flask(__name__, root_path=APP_ROOT, template_folder=APP_TEMPLATES, static_folder=APP_STATIC)
TypeError: __init__() got an unexpected keyword argument 'root_path'
```

**Comment by fnoop** [comment]
So Raspbian provides ancient version of pip and other python modules.  Altered manifests to upgrade pip and other python modules that were stopping mavcesium from running.
